config:
  payload:
    logging:
      level:
        org.springframework: ERROR
        com.payload: DEBUG
    spring:
      profiles:
        active: dev
    server:
      port: 8880
  billing:
    logging:
      level:
        org.springframework: ERROR
        com.biling: ERROR
    spring:
      profiles:
        active: dev
    server:
      port: 8881
